#!/bin/bash
# =============================================================================
# Configure Deployer Permissions for Production CI/CD
# =============================================================================
# Purpose: Grant deployer user minimum required permissions for automated deployments
# Security: Uses sudo whitelist approach with path restrictions
# Idempotent: Can be run multiple times safely
#
# Usage: sudo ./configure_deployer_permissions.sh [--dry-run]
# =============================================================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SUDOERS_FILE="/etc/sudoers.d/deployer"
BACKUP_DIR="/var/backups/sudoers"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
DRY_RUN=false

# Parse arguments
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
    echo -e "${YELLOW}[DRY RUN MODE]${NC} No changes will be made"
    echo ""
fi

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

fail() {
    log_error "$1"
    exit 1
}

# Require root
if [ "$(id -u)" -ne 0 ] && [ "$DRY_RUN" = false ]; then
    fail "This script must be run as root (use sudo)"
fi

echo "=== Configure Deployer Permissions for CI/CD ==="
echo "Date: $(date -Iseconds)"
echo "Target: Production Server (odoo18-prod)"
echo ""

# =============================================================================
# Step 1: Verify deployer user exists
# =============================================================================
log_step "Step 1: Verify deployer user exists"

if ! id deployer &>/dev/null; then
    fail "deployer user does not exist. Please run server bootstrap first."
fi

log_info "✅ deployer user exists (uid=$(id -u deployer))"
echo ""

# =============================================================================
# Step 2: Backup existing sudoers configuration
# =============================================================================
log_step "Step 2: Backup existing sudoers configuration"

if [ "$DRY_RUN" = false ]; then
    mkdir -p "$BACKUP_DIR"

    if [ -f "$SUDOERS_FILE" ]; then
        BACKUP_FILE="$BACKUP_DIR/deployer.sudoers.backup.$TIMESTAMP"
        cp "$SUDOERS_FILE" "$BACKUP_FILE"
        log_info "✅ Backed up existing config to: $BACKUP_FILE"
    else
        log_warn "No existing sudoers file found (first time setup)"
    fi
else
    log_info "[DRY RUN] Would backup $SUDOERS_FILE to $BACKUP_DIR"
fi

echo ""

# =============================================================================
# Step 3: Create new sudoers configuration
# =============================================================================
log_step "Step 3: Create new sudoers configuration"

# Define the new sudoers content
# Security principles:
# 1. Whitelist specific commands only
# 2. Use absolute paths
# 3. Restrict docker commands to specific actions and directories
# 4. No wildcard (*) for dangerous commands
# 5. NOPASSWD for automation (deployer has no password)

read -r -d '' SUDOERS_CONTENT << 'EOF' || true
# =============================================================================
# Deployer User - Production CI/CD Permissions
# =============================================================================
# Generated by: configure_deployer_permissions.sh
# Purpose: Enable automated deployments via GitHub Actions
# Security: Minimum required permissions for CI/CD workflow
# =============================================================================

# Default settings for deployer
Defaults:deployer !requiretty
Defaults:deployer !env_reset
Defaults:deployer !env_keep

# =============================================================================
# Read-only monitoring (existing permissions)
# =============================================================================
deployer ALL=(root) NOPASSWD: /usr/local/sbin/prod_status.sh
deployer ALL=(root) NOPASSWD: /usr/local/sbin/prod_logs.sh *

# =============================================================================
# Manual promotion (existing permission)
# =============================================================================
deployer ALL=(root) NOPASSWD: /usr/local/sbin/prod_promote.sh *

# =============================================================================
# Automated deployment (NEW - for CI/CD)
# =============================================================================
# Allow running deploy.sh with any arguments
deployer ALL=(root) NOPASSWD: /opt/seisei-odoo-addons/scripts/deploy.sh *

# Allow docker login for GHCR only
deployer ALL=(root) NOPASSWD: /usr/bin/docker login ghcr.io *

# Allow docker compose in deployment directories
deployer ALL=(root) NOPASSWD: /usr/bin/docker compose -f /srv/stacks/odoo18-prod/* *
deployer ALL=(root) NOPASSWD: /usr/bin/docker compose -f /srv/releases/* *

# Allow docker inspect and ps for verification
deployer ALL=(root) NOPASSWD: /usr/bin/docker inspect *
deployer ALL=(root) NOPASSWD: /usr/bin/docker ps *

# =============================================================================
# Explicitly DENIED commands (security hardening)
# =============================================================================
# Note: These are denied even if deployer somehow gets other sudo access
deployer ALL=(root) !NOPASSWD: /usr/bin/docker exec *
deployer ALL=(root) !NOPASSWD: /usr/bin/docker run *
deployer ALL=(root) !NOPASSWD: /usr/bin/docker rm *
deployer ALL=(root) !NOPASSWD: /bin/bash
deployer ALL=(root) !NOPASSWD: /bin/sh
deployer ALL=(root) !NOPASSWD: /usr/bin/sudo su
EOF

log_info "Generated new sudoers configuration:"
echo "---"
echo "$SUDOERS_CONTENT"
echo "---"
echo ""

# =============================================================================
# Step 4: Validate sudoers syntax
# =============================================================================
log_step "Step 4: Validate sudoers syntax"

if [ "$DRY_RUN" = false ]; then
    # Write to temporary file for validation
    TEMP_FILE=$(mktemp)
    echo "$SUDOERS_CONTENT" > "$TEMP_FILE"

    if visudo -c -f "$TEMP_FILE" >/dev/null 2>&1; then
        log_info "✅ Sudoers syntax is valid"
    else
        rm "$TEMP_FILE"
        fail "❌ Sudoers syntax validation FAILED. Aborting."
    fi

    rm "$TEMP_FILE"
else
    log_info "[DRY RUN] Would validate sudoers syntax"
fi

echo ""

# =============================================================================
# Step 5: Apply new sudoers configuration
# =============================================================================
log_step "Step 5: Apply new sudoers configuration"

if [ "$DRY_RUN" = false ]; then
    echo "$SUDOERS_CONTENT" > "$SUDOERS_FILE"
    chmod 0440 "$SUDOERS_FILE"
    chown root:root "$SUDOERS_FILE"

    log_info "✅ Sudoers configuration applied to: $SUDOERS_FILE"
    log_info "   Permissions: $(stat -c '%a' $SUDOERS_FILE) (owner: $(stat -c '%U:%G' $SUDOERS_FILE))"
else
    log_info "[DRY RUN] Would write to $SUDOERS_FILE with mode 0440"
fi

echo ""

# =============================================================================
# Step 6: Verify permissions
# =============================================================================
log_step "Step 6: Verify deployer permissions"

if [ "$DRY_RUN" = false ]; then
    log_info "Checking deployer sudo permissions..."

    # Run sudo -l as deployer to verify
    sudo -u deployer sudo -l > /tmp/deployer_permissions.txt 2>&1 || true

    # Check for required permissions
    REQUIRED_CMDS=(
        "/usr/local/sbin/prod_status.sh"
        "/opt/seisei-odoo-addons/scripts/deploy.sh"
        "/usr/bin/docker login ghcr.io"
        "/usr/bin/docker compose"
    )

    ALL_FOUND=true
    for cmd in "${REQUIRED_CMDS[@]}"; do
        if grep -q "$cmd" /tmp/deployer_permissions.txt; then
            log_info "  ✅ $cmd"
        else
            log_error "  ❌ $cmd NOT FOUND"
            ALL_FOUND=false
        fi
    done

    rm -f /tmp/deployer_permissions.txt

    if [ "$ALL_FOUND" = true ]; then
        log_info "✅ All required permissions verified"
    else
        log_warn "⚠️  Some permissions may not be configured correctly"
    fi
else
    log_info "[DRY RUN] Would verify deployer can run required commands"
fi

echo ""

# =============================================================================
# Summary
# =============================================================================
echo "=== Summary ==="
echo ""

if [ "$DRY_RUN" = true ]; then
    echo "DRY RUN completed. No changes were made."
    echo ""
    echo "To apply changes, run:"
    echo "  sudo $0"
else
    echo "✅ Configuration applied successfully"
    echo ""
    echo "Deployer permissions updated:"
    echo "  - Read-only monitoring: prod_status.sh, prod_logs.sh"
    echo "  - Manual promotion: prod_promote.sh"
    echo "  - Automated deployment: deploy.sh (NEW)"
    echo "  - Docker operations: login, compose, inspect, ps (NEW)"
    echo ""
    echo "Backup saved to:"
    echo "  $BACKUP_DIR/deployer.sudoers.backup.$TIMESTAMP"
    echo ""
    echo "Rollback command (if needed):"
    echo "  sudo cp $BACKUP_DIR/deployer.sudoers.backup.$TIMESTAMP $SUDOERS_FILE"
fi

echo ""
echo "=== Next Steps ==="
echo "1. Test deployer permissions:"
echo "   ssh -i <key> deployer@server 'sudo -l'"
echo ""
echo "2. Test deployment workflow:"
echo "   Trigger GitHub Actions deploy workflow"
echo ""
echo "3. Monitor deployment logs:"
echo "   gh run watch <run-id>"
echo ""

exit 0
