# -*- coding: utf-8 -*-

import logging
import json
from odoo import http, _
from odoo.http import request

_logger = logging.getLogger(__name__)


class SeiseiPrinterProxyController(http.Controller):
    """
    Additional endpoints for Seisei printer integration.
    """

    @http.route('/seisei_pos_printer/print_receipt', type='json', auth='user')
    def print_receipt(self, printer_id, escpos_data):
        """
        Print receipt via Seisei Print Manager (called from frontend).
        
        Args:
            printer_id: seisei.printer ID
            escpos_data: Base64 encoded ESC/POS commands (generated by frontend)
            
        Returns:
            dict: Result with job_id or error
        """
        try:
            seisei_printer = request.env['seisei.printer'].browse(printer_id)
            if not seisei_printer.exists():
                return {'error': 'Printer not found'}
            
            # Create print job with ESC/POS commands from frontend
            job_vals = {
                'name': _('POS Cloud Receipt Print'),
                'printer_id': seisei_printer.id,
                'type': 'pos_receipt_print',
                'is_test': False,
                'metadata': json.dumps({
                    'source': 'pos_frontend',
                    'action': 'print_receipt',
                    'doc_data': escpos_data,
                    'doc_format': 'escpos',
                }),
            }
            
            job = request.env['seisei.print.job'].sudo().create(job_vals)
            
            # Process the job
            job.action_process()
            
            _logger.info("Created cloud print job: %s for printer: %s", job.job_id, seisei_printer.name)
            
            return {'success': True, 'job_id': job.job_id}
            
        except Exception as e:
            _logger.error("Error in cloud print_receipt: %s", str(e))
            return {'error': str(e)}

    @http.route('/seisei_pos_printer/open_cashbox', type='json', auth='user')
    def open_cashbox(self, printer_id, escpos_data):
        """
        Open cash drawer via Seisei Print Manager (called from frontend).
        
        Args:
            printer_id: seisei.printer ID
            escpos_data: Base64 encoded ESC/POS commands (generated by frontend)
            
        Returns:
            dict: Result with success or error
        """
        try:
            seisei_printer = request.env['seisei.printer'].browse(printer_id)
            if not seisei_printer.exists():
                return {'error': 'Printer not found'}
            
            # Create cashbox job with ESC/POS commands from frontend
            job_vals = {
                'name': _('POS Cloud Cash Drawer'),
                'printer_id': seisei_printer.id,
                'type': 'pos_cashbox',
                'is_test': False,
                'metadata': json.dumps({
                    'source': 'pos_frontend',
                    'action': 'cashbox',
                    'doc_data': escpos_data,
                    'doc_format': 'escpos',
                }),
            }
            
            job = request.env['seisei.print.job'].sudo().create(job_vals)
            
            # Process the job
            job.action_process()
            
            _logger.info("Created cloud cashbox job: %s for printer: %s", job.job_id, seisei_printer.name)
            
            return {'success': True, 'job_id': job.job_id}
            
        except Exception as e:
            _logger.error("Error in cloud open_cashbox: %s", str(e))
            return {'error': str(e)}

    @http.route('/seisei_printer/check_printer', type='json', auth='user')
    def check_printer(self, printer_id):
        """
        Check if a POS printer is configured for Seisei printing.
        
        Args:
            printer_id: pos.printer ID
            
        Returns:
            dict: Printer configuration or None
        """
        pos_printer = request.env['pos.printer'].browse(printer_id)
        if not pos_printer.exists():
            return {'error': 'Printer not found'}
        
        if pos_printer.printer_type != 'seisei':
            return {'seisei_enabled': False}
        
        if not pos_printer.seisei_printer_id:
            return {'seisei_enabled': False, 'error': 'No Seisei printer associated'}
        
        seisei_printer = pos_printer.seisei_printer_id
        return {
            'seisei_enabled': True,
            'seisei_printer_id': seisei_printer.id,
            'printer_name': seisei_printer.name,
            'station_code': seisei_printer.station_code,
            'status': seisei_printer.status,
        }

    @http.route('/seisei_printer/get_printers', type='json', auth='user')
    def get_printers(self):
        """
        Get list of available Seisei printers.
        
        Returns:
            list: List of printer configurations
        """
        printers = request.env['seisei.printer'].search([('active', '=', True)])
        return [{
            'id': p.id,
            'name': p.name,
            'station_code': p.station_code,
            'status': p.status,
        } for p in printers]
